name: run main.py

on:
  workflow_dispatch

jobs:
  test_current_week:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'
      - run: python main.py
