name: run main.py

on:
  workflow_dispatch

jobs:
  test_current_week:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'
      - shell: bash
        env:
          SECRET_PWD_CAL: ${{ secrets.SecretPwdCal }}
        run: |
          wget https://4dEZ54Cdjr6AiR2:"$SECRET_PWD_CAL"@nextcloud.blocbox.de/public.php/webdav  -O test.cal
      - run: python main.py
